# Generated by Django 2.0.6 on 2019-02-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('alcoholPercent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('glass', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
